? create localhost<Space>;
? create localhost:repo<Base<Repo>>;
? create localhost:repo:tutorial<ArtifactBundleSeries>;
? publish ^[ bundle.zip ]-> localhost:repo:tutorial:3.0.0;
set localhost{ +bind=localhost:repo:tutorial:3.0.0:/bind/localhost.bind };
? create localhost:my-app<App>{ +config=localhost:repo:tutorial:3.0.0:/config/my-app.app,
                                +bind=localhost:repo:tutorial:3.0.0:/bind/app.bind };


