[package]
name = "email_validator_util"
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
description.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.58.0"
email_address = "0.2.9"
