version:
	$(MAKE) -C cosmic-nom
	$(MAKE) -C cosmic-macros-primitive
	$(MAKE) -C cosmic-universe

publish-dry-run:
	$(MAKE) -C cosmic-nom publish-dry-run
	$(MAKE) -C cosmic-macros-primitive publish-dry-run
	$(MAKE) -C cosmic-universe publish-dry-run

publish:
	#$(MAKE) -C cosmic-nom publish
	#$(MAKE) -C cosmic-macros-primitive publish
	$(MAKE) -C cosmic-universe publish
 
