[package]
name = "starlane-package"
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
description.workspace = true
version.workspace = true

[dependencies]
starlane-space = { workspace = true, features = ["types2"] }
starlane-base = { workspace = true }
thiserror = { workspace = true }
zip = { workspace = true, default-features = false, features = ["bzip2"] }
tempfile = { workspace = true }
derive_builder={workspace = true,optional = true}
once_cell = {workspace = true}
walkdir = {workspace = true}
reqwest = {workspace=true, features=["multipart"] }
anyhow = "1.0.99"
tokio = "1.47.1"
toml = {workspace = true}
serde = { workspace = true }
serde_derive = {workspace = true}
async-trait={workspace = true}
axum = {workspace = true, version = "1.0.0", features = ["multipart"] }
axum-core = {workspace = true}
axum-test= {workspace = true}
strum = {workspace = true}
strum_macros = {workspace = true}