[package]
name = "starlane-package"
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
description.workspace = true
version.workspace = true

[features]
default=["create"]
create=["dep:zip","dep:walkdir"]
process=["create"]
store=[]
cache=[]
daemon=[]

[dependencies]
starlane-space = {workspace=true, features=["types2"]}
thiserror = {workspace = true}
walkdir= { workspace=true,  optional = true}
zip = { workspace=true, optional=true, default-features=false,  features=["bzip2"]}