version:
	$(MAKE) -C mechtron version
	$(MAKE) -C mechtron-host version

publish-dry-run:
	$(MAKE) -C mechtron publish-dry-run
	$(MAKE) -C mechtron-host publish-dry-run

publish:
	$(MAKE) -C mechtron publish
	$(MAKE) -C mechtron-host publish

