name: Rust

on:
  push:
    branches: [ "stage" ]
  pull_request:
    branches: [ "stage" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --package starlane --verbose
#    - name: Run tests
#      run: cargo test --verbose --workspace
    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: starlane
        path:   target/${{ matrix.BUILD_TARGET }}/starlane
