name: Rust

on:
  push:
    branches: [ "stage" ]
  pull_request:
    branches: [ "stage" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TARGET: [release] 

    steps:
    - uses: actions/checkout@v4
    - name: download mac target
      run: rustup target add aarch64-apple-darwin
    - name: Build
      run: cargo build --target aarch64-apple-darwin --package starlane --verbose
#    - name: Run tests
#      run: cargo test --verbose --workspace
    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: starlane
        path:   target/aarch64-apple-darwin/${{ matrix.BUILD_TARGET }}/starlane
